apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespcae: demo 
spec:
  selector:
    app: myapp
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP 
  type: ClusterIP
